### ISSUE TITLE
couple of issues

### ISSUE THREAD

**Issue by bsr203** [prometheusresearch/webtest#3]
last change to skip `node_modules` causes issue.

```
TypeError: Cannot read property 'filter' of undefined
    at callee$1$0$ (/Users/bsr/.//webtest/node_modules/webtest/lib/index.js:89:24)
    at tryCatch (/Users/bsr/.//webtest/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/bsr/.//webtest/node_modules/babel-runtime/regenerator/runtime.js:294:22)
```

Also, parsing `config` is not done right. `config` is never assigned, but `args.config` is.
line: 82

```
 -  config = require(path.join(context,config));
 + config = require(path.join(context, args.config));
```

**Comment by bsr203** [comment]
thanks for the changes to config parsing. I tried the current version, but cannot use as `webtest` exit with `TypeError`as mentioned above.

```
TypeError: Cannot read property 'filter' of undefined
    at callee$1$0$ (/Users/bsr/.../node_modules/webtest/lib/index.js:95:24)
    at tryCatch (/usr/local/lib/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at /usr/local/lib/node_modules/babel-runtime/regenerator/runtime.js:165:16
    at run (/usr/local/lib/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:39)
    at /usr/local/lib/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:98:28
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by andreypopp** [comment]
Should be fixed now, I used older version of `babel` with newer dep on `babel-runtime`. Also I pubslished the package under `@prometheusresearch/webtest` on npm.

**Comment by bsr203** [comment]
thanks.. works great!
